// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"time"
)

type MonitoringLocation struct {
	ID        int32  `json:"id"`
	Provinsi  string `json:"provinsi"`
	Kecamatan string `json:"kecamatan"`
	Desa      string `json:"desa"`
}

type Sensor struct {
	ID              int64     `json:"id"`
	TipeSensorID    int32     `json:"tipe_sensor_id"`
	MonLocID        int32     `json:"mon_loc_id"`
	Status          bool      `json:"status"`
	DitempatkanPada time.Time `json:"ditempatkan_pada"`
}

type TipeSensor struct {
	ID     int32  `json:"id"`
	Tipe   string `json:"tipe"`
	Satuan string `json:"satuan"`
}

type ValueSensor struct {
	ID         int64     `json:"id"`
	SensorID   int32     `json:"sensor_id"`
	Data       float64   `json:"data"`
	DibuatPada time.Time `json:"dibuat_pada"`
}
